version: '3.1'

services:

  db:
    image: mysql:8.0.3
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: CHANGE_ME
      MYSQL_DATABASE: owncloud
      MYSQL_USER: owncloud
      MYSQL_PASSWORD: CHANGE_ME

  owncloud:
    depends_on:
      - db
    image: owncloud
    ports:
      - "8000:80"
    restart: always
    volumes:
      - owncloud_data:/var/www/html
    links:
      - db

volumes:
  db_data:
  owncloud_data:
